name: Compatibility Report
description: Report how well a game runs on Citron.
labels: ["compatibility"]
body:
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: How well does the game run?
      options:
        - "Perfect"
        - "Playable"
        - "Ingame"
        - "Intro/Menu"
        - "Won't Boot"
    validations:
      required: true
  - type: dropdown
    id: build_type
    attributes:
      label: Build Type
      description: Which version of Citron are you using? Please use the very latest releases when submitting a report.
      options:
        - "Stable"
        - "Nightly"
    validations:
      required: true
  - type: input
    id: cpu
    attributes:
      label: CPU
      placeholder: "e.g. Intel Core i7-13700K / Ryzen 7 7800X3D"
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: GPU
      placeholder: "e.g. NVIDIA RTX 4070 / AMD Radeon RX 7900 XT"
    validations:
      required: true
  - type: input
    id: title_id
    attributes:
      label: Title ID
      placeholder: "e.g. 0100000000010000"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: User Notes & Specs
      placeholder: "Tell us about any glitches or extra information. If you're manually submitting, ensure the issue title is the game's full name. Please share your settings .json (Right-click game > Properties > Share Settings)."
    validations:
      required: false
